name: conjur-action

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  authn-jwt:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - uses: actions/checkout@v1
      - name: Use CyberArk Conjur Secret Fetcher w/ GitHub JWT
        uses: ./
        with:
          url: https://conjurcloudint.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: github_testing
          secrets: data/vault/IF_Safe_Pavan/safe/username|sql_username;data/vault/IF_Safe_Pavan/safe/password|sql_password;
      - name: Check SQL_USERNAME Outside Docker Container for Secret Masking
        run: printenv SQL_USERNAME | sed 's/./& /g'
      - name: Check SQL_PASSWORD Outside Docker Container for Secret Masking
        run: printenv SQL_PASSWORD | sed 's/./& /g'
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

  # github-secrets:
  #   runs-on: self-hosted
    # needs: authn-jwt
    # steps:
    #   - uses: actions/checkout@v1
    #   - name: Use CyberArk Conjur Secret Fetcher w/ GitHub Secrets
    #     uses: ./
    #     with:
    #       url: https://ec2-13-217-222-17.compute-1.amazonaws.com/api
    #       account: conjur
    #       host_id: host/data/ansible/ansible-master
    #       api_key: 1mmwjwwf5xhq22hkhvjd1hxkd741djs6wq108rpnd2y0sk7y1s3p7ch
    #       secrets: data/vault/IF_Safe_Pavan/safe/username|sql_username;data/vault/IF_Safe_Pavan/safe/password|sql_password;
    #       certificate: >-
    #         -----BEGIN CERTIFICATE-----
    #         MIIDnjCCAoagAwIBAgIIPvQysXb9/WwwDQYJKoZIhvcNAQELBQAwYzERMA8GA1UE
    #         ChMIQ3liZXJBcmsxGjAYBgNVBAsTEUNvbmp1ciBDbG91ZCBFZGdlMTIwMAYDVQQD
    #         EyllYzItMTMtMjE3LTIyMi0xNy5jb21wdXRlLTEuYW1hem9uYXdzLmNvbTAeFw0y
    #         NTA1MjYwNjE3MjNaFw0yNzA2MjUwNjE3MjNaMGMxETAPBgNVBAoTCEN5YmVyQXJr
    #         MRowGAYDVQQLExFDb25qdXIgQ2xvdWQgRWRnZTEyMDAGA1UEAxMpZWMyLTEzLTIx
    #         Ny0yMjItMTcuY29tcHV0ZS0xLmFtYXpvbmF3cy5jb20wggEiMA0GCSqGSIb3DQEB
    #         AQUAA4IBDwAwggEKAoIBAQDVYDxKu8Gj4AXR7Csq2BVjOa4RWEfFMMViSBNv0+lU
    #         aFI0mlqJwaMyTkW8Lg3+557CpSOrHapoPdbTCWQhCbXVLxY4qLo39W5hIRPCMxOc
    #         85tHoadoWdyewMlVNaRjukDZP8TOcA5AYRFvKeoAffSaiAsgwfdClQDlWY1BSosx
    #         vo19dr2xabOhXC6ERxdzKhjIG6KKT5AeXqusmsC6YPp4nhBBvkPI303GmDrwsx/7
    #         Jvy7CTJIXrKhX3kSqdV74umLh0VCwQdVpzNAm5dC+5LulQuhVOl2aoLR7vqRirtv
    #         oVc5EN/fXUAnB4yrFlco9gWqo2WFRZm6Q6OK/8ERVZN/AgMBAAGjVjBUMA4GA1Ud
    #         DwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMDQGA1UdEQQtMCuCKWVjMi0xMy0yMTct
    #         MjIyLTE3LmNvbXB1dGUtMS5hbWF6b25hd3MuY29tMA0GCSqGSIb3DQEBCwUAA4IB
    #         AQA0ozpRmidEeXpQuEzRKvgxm3CVFmnijqcmQLmpWL4CqfhoOrrz9Y8uZmfRzs56
    #         /BtqywTj2upzVBZ6+pjdm6Dh7o6sfD13fBlKVR57SxWUX/8wTk76ovuzo2CU3pNv
    #         h4/mviJsCzY2BJi1wYHxlmLdFlY5RxWGrbWdJII8mFJuIMj9bNwRfgHnE4jPgQa1
    #         zPJE1x/uo6N3Np0y5mP89O9KBDrjW6UlIig94fvRyfUDxHN+jGtjEJ5cFYQLjhpS
    #         1V+ZuYC7mQoiAXP1VIfYMjuAi7JPgFe15JNTVkHb2j7prca2hiITIb7jFIKuc8YT
    #         RtMCmcnqzUXYca/83iXpttCu
    #         -----END CERTIFICATE-----  
            
    #   - name: Check SQL_USERNAME Outside Docker Container for Secret Masking
    #     run: printenv SQL_USERNAME | sed 's/./& /g'
    #   - name: Check SQL_PASSWORD Outside Docker Container for Secret Masking
    #     run: printenv SQL_PASSWORD | sed 's/./& /g'
    #   - name: Clean Workspace
    #     uses: AutoModality/action-clean@v1.1.0



